-- One-time cleanup of historical MVP seed/demo records.
-- Safe to re-run: deletes only known seeded patterns/names.

DO $$
DECLARE
  v_seed_package_names text[] := ARRAY[
    'Starter Health 20',
    'Growth Health 50',
    'Starter Life 20',
    'Starter Auto 20',
    'Starter Debt 20'
  ];
  v_seed_offer_titles text[] := ARRAY[
    'Welcome Offer - Health',
    'Launch Offer - Life'
  ];
BEGIN
  -- 1) Collect seeded inventory leads generated by 20260417170000_customer_seed.sql.
  CREATE TEMP TABLE tmp_seed_lead_ids ON COMMIT DROP AS
  SELECT l.id
  FROM public.leads l
  WHERE COALESCE(l.summary, '') ILIKE 'Seeded lead for %';

  -- 2) Collect seeded package ids.
  CREATE TEMP TABLE tmp_seed_package_ids ON COMMIT DROP AS
  SELECT lp.id
  FROM public.lead_packages lp
  WHERE lp.name = ANY (v_seed_package_names);

  -- 3) Delete routing events tied to seeded inventory (FK RESTRICT on leads).
  DELETE FROM public.delivery_routing_events dre
  USING tmp_seed_lead_ids s
  WHERE dre.source_lead_id = s.id;

  -- 4) Delete ledger lines for customer leads coming from seeded inventory.
  DELETE FROM public.delivery_ledger_lines dll
  USING public.customer_leads cl, tmp_seed_lead_ids s
  WHERE dll.customer_lead_id = cl.id
    AND cl.source_lead_id = s.id;

  -- 5) Delete customer leads delivered from seeded inventory.
  DELETE FROM public.customer_leads cl
  USING tmp_seed_lead_ids s
  WHERE cl.source_lead_id = s.id;

  -- 6) Delete recurring flows that point to seeded packages (commitments cascade).
  DELETE FROM public.customer_lead_flows f
  USING tmp_seed_package_ids p
  WHERE f.package_id = p.id;

  -- 7) Delete purchases for seeded packages (customer_leads cascade if any remain).
  DELETE FROM public.lead_purchases lpur
  USING tmp_seed_package_ids p
  WHERE lpur.package_id = p.id;

  -- 8) Delete seeded offers/packages.
  DELETE FROM public.lead_offers lo
  WHERE lo.title = ANY (v_seed_offer_titles);

  DELETE FROM public.lead_packages lp
  USING tmp_seed_package_ids p
  WHERE lp.id = p.id;

  -- 9) Delete seeded inventory rows themselves.
  DELETE FROM public.leads l
  USING tmp_seed_lead_ids s
  WHERE l.id = s.id;
END $$;

-- Optional follow-up (manual): remove old seed categories if they are empty/orphaned.
-- DELETE FROM public.categories c
-- WHERE c.slug IN ('health-insurance', 'life-insurance', 'auto-insurance', 'debt-relief')
--   AND NOT EXISTS (SELECT 1 FROM public.leads l WHERE l.category_id = c.id)
--   AND NOT EXISTS (SELECT 1 FROM public.lead_packages lp WHERE lp.category_id = c.id)
--   AND NOT EXISTS (SELECT 1 FROM public.lead_pricebook pb WHERE pb.category_id = c.id);
